# Generated by Django 3.1.6 on 2021-02-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='blog_app.postcategory'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='t_posts',
        ),
        migrations.AlterModelTable(
            name='postcategory',
            table='t_post_categories',
        ),
        migrations.AlterModelTable(
            name='postcomment',
            table='t_post_comments',
        ),
    ]
