# Generated by Django 3.1.6 on 2021-02-07 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_postcomment_commenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='commenter_email',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='commenter_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
